model_name: basic_cnn
input_shape: [28, 28, 1]
num_classes: 10

conv_layers:
  - filters: 32
    kernel_size: [3, 3]
    activation: relu
    batch_norm: true
    max_pool: true
  - filters: 64
    kernel_size: [3, 3]
    activation: relu
    batch_norm: true
    max_pool: true

dense_layers:
  - units: 128
    activation: relu
    dropout_rate: 0.5

output_layer:
  activation: softmax

optimizer:
  type: adam
  learning_rate: 0.001

loss: sparse_categorical_crossentropy
metrics:
  - accuracy

batch_size: 64
epochs: 10
